/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { CertificateRegistry, CertificateRegistryInterface } from "../CertificateRegistry.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "hash",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "submitter",
        "type": "address"
      }
    ],
    "name": "CertificateStored",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "name": "certificateHashes",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "hash",
        "type": "bytes32"
      }
    ],
    "name": "storeHash",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "hash",
        "type": "bytes32"
      }
    ],
    "name": "verifyHash",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5061030f8061001c5f395ff3fe608060405234801561000f575f5ffd5b506004361061003f575f3560e01c80637fe8888514610043578063bedda47e1461005f578063ef020f4a1461008f575b5f5ffd5b61005d60048036038101906100589190610203565b6100bf565b005b61007960048036038101906100749190610203565b61018b565b6040516100869190610248565b60405180910390f35b6100a960048036038101906100a49190610203565b6101a7565b6040516100b69190610248565b60405180910390f35b5f5f8281526020019081526020015f205f9054906101000a900460ff161561011c576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401610113906102bb565b60405180910390fd5b60015f5f8381526020019081526020015f205f6101000a81548160ff0219169083151502179055503373ffffffffffffffffffffffffffffffffffffffff16817f68c57ee07187efc88a54ed1e3d4105b6e7d0f49dcb887c87bb1caca9bf2c0ce560405160405180910390a350565b5f602052805f5260405f205f915054906101000a900460ff1681565b5f5f5f8381526020019081526020015f205f9054906101000a900460ff169050919050565b5f5ffd5b5f819050919050565b6101e2816101d0565b81146101ec575f5ffd5b50565b5f813590506101fd816101d9565b92915050565b5f60208284031215610218576102176101cc565b5b5f610225848285016101ef565b91505092915050565b5f8115159050919050565b6102428161022e565b82525050565b5f60208201905061025b5f830184610239565b92915050565b5f82825260208201905092915050565b7f436572746966696361746520616c72656164792073746f7265640000000000005f82015250565b5f6102a5601a83610261565b91506102b082610271565b602082019050919050565b5f6020820190508181035f8301526102d281610299565b905091905056fea264697066735822122049482777918c3df5100b5bb609936918632bf3d5bee40691d0b51ab0cffb650564736f6c634300081c0033";

  
      type CertificateRegistryConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: CertificateRegistryConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class CertificateRegistry__factory extends ContractFactory {
    
      constructor(...args: CertificateRegistryConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<CertificateRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): CertificateRegistry__factory {
      return super.connect(runner) as CertificateRegistry__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): CertificateRegistryInterface {
      return new Interface(_abi) as CertificateRegistryInterface;
    }
    
    override attach(address: string | Addressable): CertificateRegistry {
      return super.attach(address) as CertificateRegistry;
    }
  static connect(address: string, runner?: ContractRunner | null): CertificateRegistry {
      return new Contract(address, _abi, runner) as unknown as CertificateRegistry;
    }
  }

  
  